version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: main_mysql_8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - mysqlnetwork

  adminer:
    image: adminer
    container_name: main_adminer
    restart: always
    ports:
      - "8050:8080"
    networks:
      - mysqlnetwork

volumes:
  mysqldata:

networks:
  mysqlnetwork: